format = "$directory$git_branch$character"
right_format = "$time"

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[directory]
truncation_length = 1

[git_branch]
style = 'bold red'

[time]
style = "bold blue"
